config/routes.rb
Rails.application.routes.draw do

  root to: "collections#index"
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'collections/all_collections', to: 'collections#all_collections'
  resources :collections do
    resources :imgs
    resources :links
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base

  belongs_to :user
  has_many :imgs, dependent: :destroy
  has_many :links, dependent: :destroy
  accepts_nested_attributes_for :imgs, :links

end

app/models/img.rb
class Img < ActiveRecord::Base

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  belongs_to :collection

end

app/models/link.rb
class Link < ActiveRecord::Base

  belongs_to :collection
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :collections

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!

  # /collections
  def index
    @collections = Collection.where(user_id: current_user.id)
  end

  # /collections/:id
  def show
    @collection = Collection.find(params[:id])
    @imgs = Img.where(collection_id: @collection.id)
    @links = Link.where(collection_id: @collection.id)
  end

  # /collections/new
  def new
    @collection = Collection.new()
  end

  # /collections
  def create
    #collection_params = params.require(:collection).permit(:name)
    @collection = Collection.create(collection_params)
    @collection.update_attributes(user_id: current_user.id)
    # @collection.user_id = current_user.id
    if @collection.errors.empty?
      redirect_to collection_path(@collection) #/collection/:id
    else
      render "new"
    end
  end

  # /collections/:id/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # /collections/:id
  def update
    @collection = Collection.find(params[:id])
    @collection.update(collection_params)
    if @collection.errors.empty?
      redirect_to collection_path(params[:id]) #/collection/:id
    else
      render "edit"
    end
  end

  # /collections/:id
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    redirect_to action: "index"
  end

  def all_collections
    @collections = Collection.all
    render "index"
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  # #  def set_post
  # #    @post = Post.find(params[:id])
  # #  end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
     def collection_params
       params.require(:collection).permit(:name, :kind, :description)
     end
end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController

  before_action :authenticate_user!

  # /collections
  def index
    redirect_to collections_url
  end

  # /collections/:id
  def show
    @img = Img.find(params[:id])
  end

  # /collections/new
  def new
    @collection = Collection.find(params[:collection_id])
    @img = Img.new()
  end

  # /collections
  def create
    @collection = Collection.find(params[:collection_id])
    @img = @collection.imgs.create(img_params)
    if @img.errors.empty?
      redirect_to collection_path(@collection) #/collection/:id
    else
      render "new"
    end
  end

  # /collections/:id/edit
  def edit
    @collection = Collection.find(params[:collection_id])
    @img = Img.find(params[:id])
  end

  # /collections/:id
  def update
    @collection = Collection.find(params[:collection_id])
    @img = @collection.imgs.update(params[:id], img_params)
    if @img.errors.empty?
      redirect_to collection_path(@img.collection_id) #/collection/:id
    else
      render "edit"
    end

  end

  # /collections/:id
  def destroy
    @img = Img.find(params[:id])
    @img.destroy
    redirect_to collection_path(@img.collection_id)
  end

  private

     def img_params
       params.require(:img).permit(:name, :collection_id, :picture, :description)
     end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :authenticate_user!

  # /collections
  def index
    redirect_to collections_url
  end

  # /collections/:id
  def show
    @link = Link.find(params[:id])
  end

  # /collections/new
  def new
    @collection = Collection.find(params[:collection_id])
    @link = Link.new()
  end

  # /collections
  def create
    @collection = Collection.find(params[:collection_id])
    @link = @collection.links.create(link_params)
    if @link.errors.empty?
      redirect_to collection_path(@collection) #/collection/:id
    else
      render "new"
    end
  end

  # /collections/:id/edit
  def edit
    @collection = Collection.find(params[:collection_id])
    @link = Link.find(params[:id])
  end

  # /collections/:id
  def update
    @collection = Collection.find(params[:collection_id])
    @link = @collection.links.update(params[:id], link_params)
    if @link.errors.empty?
      redirect_to collection_path(@link.collection_id) #/collection/:id
    else
      render "edit"
    end

  end

  # /collections/:id
  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to collection_path(@link.collection_id)
  end

  private

     def link_params
       params.require(:link).permit(:name, :collection_id, :reference, :description)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/collections/_form.html.erb
<p>Collection name</br> <%= f.text_field :name %></p>
<p>Description</br><%= f.text_area :description %></p>

app/views/collections/edit.html.erb
<h2>Edit new collection</h2>

<%= form_for @collection do |f| %>

  <%=render partial: "form", locals: {f: f}%>

  <p><%= f.submit %></p>
<% end %>

app/views/collections/index.html.erb
<h2> All user collections </h2>

<% if @collections.empty?%>
  <b>the user has no collections</b>
<% else %>
  <table>
    <tr>
      <th>Collection</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @collections.each do |c| %>
    <tr>
      <td><%= link_to c.name, collection_path(c) %></td>
      <td><%= link_to 'Edit', edit_collection_path(c) %></td>
      <td><%= link_to 'Destroy', collection_path(c), method: :delete, data: { confirm: 'Are you sure?' }%></td>
    </tr>
    <% end %>
  </table>
<% end %>
<p><%= link_to "Add new collection", new_collection_path %></p>
<p><%= link_to "All collections", collections_all_collections_path %></p>

app/views/collections/new.html.erb
<h2>Create new collection</h2>

<%= form_for @collection do |f| %>

  <%=render partial: "form", locals: {f: f}%>

  <%= f.radio_button :kind, 'links' %>
  <%= f.label :kind_links, 'Links' %>
  <%= f.radio_button :kind, 'images' %>
  <%= f.label :kind_images, 'Images' %>

  <p><%= f.submit %></p>
<% end %>

app/views/collections/show.html.erb
<h2><%= @collection.name %></h2>
<p><%= @collection.description%></p>
<% if @collection.kind == "images"%>
  <table>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @imgs.each do |i| %>
    <tr>
      <td><%= link_to i.name, collection_img_path(@collection.id, i.id) %></td>
      <td><%= image_tag i.picture.url(:medium)%></td>
      <td><%= link_to 'Edit', edit_collection_img_path(@collection.id, i.id)%></td>
      <td><%= link_to 'Destroy', collection_img_path(@collection.id, i), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
  <p><%= link_to "Add new image", new_collection_img_path(@collection.id) %></p>
<% end %>

<% if @collection.kind == "links" %>
  <table>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @links.each do |l| %>
    <tr>
      <td><%= link_to l.name, collection_link_path(@collection.id, l.id) %></td>
      <td><a href="<%=l.reference%>", target="_blank"><%=l.reference%></a></td>
      <td><%= link_to 'Edit', edit_collection_link_path(@collection.id, l.id)%></td>
      <td><%= link_to 'Destroy', collection_link_path(@collection.id, l), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
  <p><%= link_to "Add new link", new_collection_link_path(@collection.id) %></p>
<% end %>

app/views/imgs/_form.html.erb
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :picture %><br>
  <%= f.file_field :picture %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>
<p><%= f.submit %></p>

app/views/imgs/edit.html.erb
<h2>Edit img</h2>

<%= form_for ([@collection, @img]) do |f| %>

  <%=render partial: "form", locals: {f: f}%>

<% end %>

app/views/imgs/new.html.erb
<h2>Create new img</h2>

<%= form_for ([@collection, @img]) do |f| %>

  <%=render partial: "form", locals: {f: f}%>

<% end %>

app/views/imgs/show.html.erb
<p><%= @img.id %></p>


<p>
  <strong>Name:</strong>
  <%= @img.name %>
</p>
<p>
  <strong>IMG</strong>
  <%= image_tag @img.picture.url(:medium) %>
</p>
<p>
  <strong>Description:</strong>
  <%= @img.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <ul>
    <% if user_signed_in? %>
        <li><%= link_to "My collections", collections_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
  </ul>
<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :reference %><br>
  <%= f.text_field :reference %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
<p><%= f.submit %></p>

app/views/links/edit.html.erb
<h2>Edit link</h2>

<%= form_for ([@collection, @link]) do |f| %>

  <%=render partial: "form", locals: {f: f}%>

<% end %>

app/views/links/new.html.erb
<h2>Create new link</h2>

<%= form_for ([@collection, @link]) do |f| %>

  <%=render partial: "form", locals: {f: f}%>

<% end %>

app/views/links/show.html.erb
<p><%= @link.name %></p>


<p>
  <strong>Name:</strong>
  <%= @link.name %>
</p>
<p>
  <strong>Link:</strong>
   <a href="<%=@link.reference%>", target="_blank"><%=@link.reference%></a>
</p>
<p>
  <strong>Description:</strong>
  <%= @link.description %>
</p>